language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly
before_script:
  - composer self-update
  - composer --no-interaction --ignore-platform-reqs install
script: phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar --no-check-certificate
  - if [[ $TRAVIS_PHP_VERSION != 'hhvm' && $TRAVIS_PHP_VERSION != '7.0' && $TRAVIS_PHP_VERSION != 'nightly' ]]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi
